FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY Portfolio.Blazor.csproj .
RUN dotnet restore "Portfolio.Blazor.csproj"
COPY . .
RUN dotnet build "Portfolio.Blazor.csproj" -c Release -f netstandard2.1

FROM build AS publish
RUN dotnet publish "Portfolio.Blazor.csproj" -c Release -f netstandard2.1

FROM nginx:alpine AS final
COPY --from=publish /src/bin/Release/netstandard2.1/publish/wwwroot /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf