name: Deploy Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy Docker Image to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          git clone https://github.com/YuKitsune/Portfolio.git
          cd Portfolio/Portfolio.Blazor
          docker build -t portfolio.blazor .
          docker run 
